import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="font-['Montserrat'] text-white bg-black h-screen w-screen relative">
      <Head>
        <title>Portfolio - Tae Lee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <div className='absolute top-0 w-screen h-20 flex px-3 py-3'>
        <div className='w-1/3 flex items-center'>
          <img src="images/profilepic.jpg" alt="profilepic" className="rounded-full w-12 h-12" />
          <h1 className="text-md font-bold ml-1">Tae Lee</h1>
        </div>
        <div className='w-2/3 flex justify-end items-center'>
          <Link href="/" className="text-sm font-semibold mr-2">Home</Link>
          <Link href="/projects" className="text-sm font-semibold mr-2">Projects</Link>
          <Link href="/contact" className="text-sm font-semibold mr-2">Contact</Link>
        </div>
      </div>
    </div>
  )
}
