import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="font-['Montserrat'] text-white bg-black h-screen w-screen ">
      <Head>
        <title>Portfolio - Tae Lee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <div className='top-0 w-screen h-20 flex px-3 py-3'>
        <div className='w-1/3 flex items-center'>
          <img src="images/profilepic.jpg" alt="profilepic" className="rounded-full w-12 h-12" />
          <h1 className="text-md font-bold ml-2">Tae Lee</h1>
        </div>
        <div className='w-2/3 flex justify-end items-center'>
          <Link href="/" className="text-sm font-semibold mr-2">Home</Link>
          <Link href="/projects" className="text-sm font-semibold mr-2">Projects</Link>
          <Link href="/contact" className="text-sm font-semibold mr-2">Contact</Link>
        </div>
      </div>
      <div className="bg-midnight w-10/12 p-4 border-2 rounded-lg mt-14 mx-auto shadow-cyan-700 shadow-lg">
        <h4 className="text-sm font-light">Highly motivated junior developer with a love for front end design. Transitioned into coding after dabbling in the web 3.0 space and audio production,
          sparking my interest when I tried to build a marketplace (website) to upload my instrumentals/beats. </h4>
        <h4 className="text-sm font-light mt-6">Decided to take the leap and hopped on the Le Wagon
          Web Development Bootcamp in 2022 (#Batch 966). Looking to work in a team to produce quality, leading-edge websites that are user-focused and
          exceptional in design</h4>
        <p className="text-sm mt-6">- Next.js, React.js, HTML, CSS, Tailwind CSS, Sass and Typescript/Javascript</p>
        <p className="text-sm mt-2">- Ruby on Rails, SQL, Heroku and GitHub</p>
        <p className="text-sm mt-2">- Relational Databasing + Active Record</p>
        <div className="flex w-full px-2 mt-8 mb-6 justify-around">
          <a className="border-2 py-2 px-5 rounded-xl active:shadow-md active:shadow-cyan-700 active:-translate-y-1 active:duration-100" href="https://www.linkedin.com/in/taelee3/" target="_blank" rel="noreferrer">Linkedin</a>
          <a className="border-2 py-2 px-5 rounded-xl active:shadow-md active:shadow-cyan-700 active:-translate-y-1 active:duration-100" href="https://github.com/taeleenz38" target="_blank" rel="noreferrer">GitHub</a>
        </div>
      </div>
    </div>
  )
}
